# Name of the GitHub Actions workflow file: .github/workflows/pdf-to-word.yml

name: Run PDF to Word Converter

# This workflow runs automatically on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    # This job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository's code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Installs the necessary Python packages from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Runs your main Python script
      # IMPORTANT: Replace 'app.py' with the actual name of your Python file!
      - name: Run the converter script
        run: python pdf-to-word.py
